// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.alextran.immich.upload

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object TusUploadPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Metadata for tus upload
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TusUploadData (
  val filePath: String,
  val filename: String,
  val serverEndpoint: String,
  val headers: Map<String, String>,
  val deviceAssetId: String,
  val deviceId: String,
  val fileCreatedAt: String,
  val fileModifiedAt: String,
  val isFavorite: Boolean,
  val duration: String? = null,
  val livePhotoVideoId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TusUploadData {
      val filePath = pigeonVar_list[0] as String
      val filename = pigeonVar_list[1] as String
      val serverEndpoint = pigeonVar_list[2] as String
      val headers = pigeonVar_list[3] as Map<String, String>
      val deviceAssetId = pigeonVar_list[4] as String
      val deviceId = pigeonVar_list[5] as String
      val fileCreatedAt = pigeonVar_list[6] as String
      val fileModifiedAt = pigeonVar_list[7] as String
      val isFavorite = pigeonVar_list[8] as Boolean
      val duration = pigeonVar_list[9] as String?
      val livePhotoVideoId = pigeonVar_list[10] as String?
      return TusUploadData(filePath, filename, serverEndpoint, headers, deviceAssetId, deviceId, fileCreatedAt, fileModifiedAt, isFavorite, duration, livePhotoVideoId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      filePath,
      filename,
      serverEndpoint,
      headers,
      deviceAssetId,
      deviceId,
      fileCreatedAt,
      fileModifiedAt,
      isFavorite,
      duration,
      livePhotoVideoId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TusUploadData) {
      return false
    }
    if (this === other) {
      return true
    }
    return TusUploadPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Progress update for tus upload
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TusProgressUpdate (
  val uploadId: String,
  val bytesUploaded: Long,
  val totalBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TusProgressUpdate {
      val uploadId = pigeonVar_list[0] as String
      val bytesUploaded = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      return TusProgressUpdate(uploadId, bytesUploaded, totalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uploadId,
      bytesUploaded,
      totalBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TusProgressUpdate) {
      return false
    }
    if (this === other) {
      return true
    }
    return TusUploadPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Status update for tus upload
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TusStatusUpdate (
  val uploadId: String,
  val status: String,
  val assetId: String? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TusStatusUpdate {
      val uploadId = pigeonVar_list[0] as String
      val status = pigeonVar_list[1] as String
      val assetId = pigeonVar_list[2] as String?
      val error = pigeonVar_list[3] as String?
      return TusStatusUpdate(uploadId, status, assetId, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uploadId,
      status,
      assetId,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TusStatusUpdate) {
      return false
    }
    if (this === other) {
      return true
    }
    return TusUploadPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class TusUploadPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TusUploadData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TusProgressUpdate.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TusStatusUpdate.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TusUploadData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is TusProgressUpdate -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is TusStatusUpdate -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for tus upload operations (Dart calls native)
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TusUploadApi {
  /**
   * Upload a file using the tus protocol
   * Returns the upload ID that can be used to track progress or cancel
   */
  fun startUpload(data: TusUploadData, callback: (Result<String>) -> Unit)
  /** Cancel an ongoing upload */
  fun cancelUpload(uploadId: String, callback: (Result<Boolean>) -> Unit)
  /** Cancel all ongoing uploads */
  fun cancelAllUploads(callback: (Result<Unit>) -> Unit)
  /** Get the current offset of an upload (for resumption) */
  fun getUploadOffset(uploadId: String, callback: (Result<Long?>) -> Unit)
  /** Check if there are any pending uploads that can be resumed */
  fun getPendingUploadIds(callback: (Result<List<String>>) -> Unit)

  companion object {
    /** The codec used by TusUploadApi. */
    val codec: MessageCodec<Any?> by lazy {
      TusUploadPigeonCodec()
    }
    /** Sets up an instance of `TusUploadApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TusUploadApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.TusUploadApi.startUpload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dataArg = args[0] as TusUploadData
            api.startUpload(dataArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TusUploadPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TusUploadPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.TusUploadApi.cancelUpload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uploadIdArg = args[0] as String
            api.cancelUpload(uploadIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TusUploadPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TusUploadPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.TusUploadApi.cancelAllUploads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cancelAllUploads{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TusUploadPigeonUtils.wrapError(error))
              } else {
                reply.reply(TusUploadPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.TusUploadApi.getUploadOffset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uploadIdArg = args[0] as String
            api.getUploadOffset(uploadIdArg) { result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TusUploadPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TusUploadPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.immich_mobile.TusUploadApi.getPendingUploadIds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPendingUploadIds{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TusUploadPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TusUploadPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter API for receiving upload callbacks (native calls Dart)
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class TusUploadCallbackApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TusUploadCallbackApi. */
    val codec: MessageCodec<Any?> by lazy {
      TusUploadPigeonCodec()
    }
  }
  /** Called when upload progress changes */
  fun onProgress(updateArg: TusProgressUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(updateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TusUploadPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Called when upload status changes */
  fun onStatusChange(updateArg: TusStatusUpdate, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onStatusChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(updateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TusUploadPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
