// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

// PigeonError class is already defined in Messages.g.swift
// Removed duplicate to avoid ambiguity errors

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsTusUpload(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsTusUpload(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsTusUpload(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashTusUpload(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashTusUpload(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashTusUpload(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Metadata for tus upload
///
/// Generated class from Pigeon that represents data sent in messages.
struct TusUploadData: Hashable {
  var filePath: String
  var filename: String
  var serverEndpoint: String
  var headers: [String: String]
  var deviceAssetId: String
  var deviceId: String
  var fileCreatedAt: String
  var fileModifiedAt: String
  var isFavorite: Bool
  var duration: String? = nil
  var livePhotoVideoId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TusUploadData? {
    let filePath = pigeonVar_list[0] as! String
    let filename = pigeonVar_list[1] as! String
    let serverEndpoint = pigeonVar_list[2] as! String
    let headers = pigeonVar_list[3] as! [String: String]
    let deviceAssetId = pigeonVar_list[4] as! String
    let deviceId = pigeonVar_list[5] as! String
    let fileCreatedAt = pigeonVar_list[6] as! String
    let fileModifiedAt = pigeonVar_list[7] as! String
    let isFavorite = pigeonVar_list[8] as! Bool
    let duration: String? = nilOrValue(pigeonVar_list[9])
    let livePhotoVideoId: String? = nilOrValue(pigeonVar_list[10])

    return TusUploadData(
      filePath: filePath,
      filename: filename,
      serverEndpoint: serverEndpoint,
      headers: headers,
      deviceAssetId: deviceAssetId,
      deviceId: deviceId,
      fileCreatedAt: fileCreatedAt,
      fileModifiedAt: fileModifiedAt,
      isFavorite: isFavorite,
      duration: duration,
      livePhotoVideoId: livePhotoVideoId
    )
  }
  func toList() -> [Any?] {
    return [
      filePath,
      filename,
      serverEndpoint,
      headers,
      deviceAssetId,
      deviceId,
      fileCreatedAt,
      fileModifiedAt,
      isFavorite,
      duration,
      livePhotoVideoId,
    ]
  }
  static func == (lhs: TusUploadData, rhs: TusUploadData) -> Bool {
    return deepEqualsTusUpload(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashTusUpload(value: toList(), hasher: &hasher)
  }
}

/// Progress update for tus upload
///
/// Generated class from Pigeon that represents data sent in messages.
struct TusProgressUpdate: Hashable {
  var uploadId: String
  var bytesUploaded: Int64
  var totalBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TusProgressUpdate? {
    let uploadId = pigeonVar_list[0] as! String
    let bytesUploaded = pigeonVar_list[1] as! Int64
    let totalBytes = pigeonVar_list[2] as! Int64

    return TusProgressUpdate(
      uploadId: uploadId,
      bytesUploaded: bytesUploaded,
      totalBytes: totalBytes
    )
  }
  func toList() -> [Any?] {
    return [
      uploadId,
      bytesUploaded,
      totalBytes,
    ]
  }
  static func == (lhs: TusProgressUpdate, rhs: TusProgressUpdate) -> Bool {
    return deepEqualsTusUpload(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashTusUpload(value: toList(), hasher: &hasher)
  }
}

/// Status update for tus upload
///
/// Generated class from Pigeon that represents data sent in messages.
struct TusStatusUpdate: Hashable {
  var uploadId: String
  var status: String
  var assetId: String? = nil
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TusStatusUpdate? {
    let uploadId = pigeonVar_list[0] as! String
    let status = pigeonVar_list[1] as! String
    let assetId: String? = nilOrValue(pigeonVar_list[2])
    let error: String? = nilOrValue(pigeonVar_list[3])

    return TusStatusUpdate(
      uploadId: uploadId,
      status: status,
      assetId: assetId,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      uploadId,
      status,
      assetId,
      error,
    ]
  }
  static func == (lhs: TusStatusUpdate, rhs: TusStatusUpdate) -> Bool {
    return deepEqualsTusUpload(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashTusUpload(value: toList(), hasher: &hasher)
  }
}

private class TusUploadPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return TusUploadData.fromList(self.readValue() as! [Any?])
    case 130:
      return TusProgressUpdate.fromList(self.readValue() as! [Any?])
    case 131:
      return TusStatusUpdate.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class TusUploadPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TusUploadData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? TusProgressUpdate {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? TusStatusUpdate {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TusUploadPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TusUploadPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TusUploadPigeonCodecWriter(data: data)
  }
}

class TusUploadPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TusUploadPigeonCodec(readerWriter: TusUploadPigeonCodecReaderWriter())
}


/// Host API for tus upload operations (Dart calls native)
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TusUploadApi {
  /// Upload a file using the tus protocol
  /// Returns the upload ID that can be used to track progress or cancel
  func startUpload(data: TusUploadData, completion: @escaping (Result<String, Error>) -> Void)
  /// Cancel an ongoing upload
  func cancelUpload(uploadId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Cancel all ongoing uploads
  func cancelAllUploads(completion: @escaping (Result<Void, Error>) -> Void)
  /// Get the current offset of an upload (for resumption)
  func getUploadOffset(uploadId: String, completion: @escaping (Result<Int64?, Error>) -> Void)
  /// Check if there are any pending uploads that can be resumed
  func getPendingUploadIds(completion: @escaping (Result<[String], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TusUploadApiSetup {
  static var codec: FlutterStandardMessageCodec { TusUploadPigeonCodec.shared }
  /// Sets up an instance of `TusUploadApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TusUploadApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Upload a file using the tus protocol
    /// Returns the upload ID that can be used to track progress or cancel
    let startUploadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.TusUploadApi.startUpload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startUploadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! TusUploadData
        api.startUpload(data: dataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startUploadChannel.setMessageHandler(nil)
    }
    /// Cancel an ongoing upload
    let cancelUploadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.TusUploadApi.cancelUpload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelUploadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uploadIdArg = args[0] as! String
        api.cancelUpload(uploadId: uploadIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelUploadChannel.setMessageHandler(nil)
    }
    /// Cancel all ongoing uploads
    let cancelAllUploadsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.TusUploadApi.cancelAllUploads\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAllUploadsChannel.setMessageHandler { _, reply in
        api.cancelAllUploads { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelAllUploadsChannel.setMessageHandler(nil)
    }
    /// Get the current offset of an upload (for resumption)
    let getUploadOffsetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.TusUploadApi.getUploadOffset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUploadOffsetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uploadIdArg = args[0] as! String
        api.getUploadOffset(uploadId: uploadIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getUploadOffsetChannel.setMessageHandler(nil)
    }
    /// Check if there are any pending uploads that can be resumed
    let getPendingUploadIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.TusUploadApi.getPendingUploadIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPendingUploadIdsChannel.setMessageHandler { _, reply in
        api.getPendingUploadIds { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPendingUploadIdsChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API for receiving upload callbacks (native calls Dart)
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol TusUploadCallbackApiProtocol {
  /// Called when upload progress changes
  func onProgress(update updateArg: TusProgressUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when upload status changes
  func onStatusChange(update updateArg: TusStatusUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class TusUploadCallbackApi: TusUploadCallbackApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: TusUploadPigeonCodec {
    return TusUploadPigeonCodec.shared
  }
  /// Called when upload progress changes
  func onProgress(update updateArg: TusProgressUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([updateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when upload status changes
  func onStatusChange(update updateArg: TusStatusUpdate, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onStatusChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([updateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
