// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Metadata for tus upload
class TusUploadData {
  TusUploadData({
    required this.filePath,
    required this.filename,
    required this.serverEndpoint,
    required this.headers,
    required this.deviceAssetId,
    required this.deviceId,
    required this.fileCreatedAt,
    required this.fileModifiedAt,
    required this.isFavorite,
    this.duration,
    this.livePhotoVideoId,
  });

  String filePath;

  String filename;

  String serverEndpoint;

  Map<String, String> headers;

  String deviceAssetId;

  String deviceId;

  String fileCreatedAt;

  String fileModifiedAt;

  bool isFavorite;

  String? duration;

  String? livePhotoVideoId;

  List<Object?> _toList() {
    return <Object?>[
      filePath,
      filename,
      serverEndpoint,
      headers,
      deviceAssetId,
      deviceId,
      fileCreatedAt,
      fileModifiedAt,
      isFavorite,
      duration,
      livePhotoVideoId,
    ];
  }

  Object encode() {
    return _toList();  }

  static TusUploadData decode(Object result) {
    result as List<Object?>;
    return TusUploadData(
      filePath: result[0]! as String,
      filename: result[1]! as String,
      serverEndpoint: result[2]! as String,
      headers: (result[3] as Map<Object?, Object?>?)!.cast<String, String>(),
      deviceAssetId: result[4]! as String,
      deviceId: result[5]! as String,
      fileCreatedAt: result[6]! as String,
      fileModifiedAt: result[7]! as String,
      isFavorite: result[8]! as bool,
      duration: result[9] as String?,
      livePhotoVideoId: result[10] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TusUploadData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Result of tus upload
class TusUploadResult {
  TusUploadResult({
    this.assetId,
    this.error,
    this.isDuplicate = false,
  });

  String? assetId;

  String? error;

  bool isDuplicate;

  List<Object?> _toList() {
    return <Object?>[
      assetId,
      error,
      isDuplicate,
    ];
  }

  Object encode() {
    return _toList();  }

  static TusUploadResult decode(Object result) {
    result as List<Object?>;
    return TusUploadResult(
      assetId: result[0] as String?,
      error: result[1] as String?,
      isDuplicate: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TusUploadResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Progress update for tus upload
class TusProgressUpdate {
  TusProgressUpdate({
    required this.uploadId,
    required this.bytesUploaded,
    required this.totalBytes,
  });

  String uploadId;

  int bytesUploaded;

  int totalBytes;

  List<Object?> _toList() {
    return <Object?>[
      uploadId,
      bytesUploaded,
      totalBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static TusProgressUpdate decode(Object result) {
    result as List<Object?>;
    return TusProgressUpdate(
      uploadId: result[0]! as String,
      bytesUploaded: result[1]! as int,
      totalBytes: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TusProgressUpdate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Status update for tus upload
class TusStatusUpdate {
  TusStatusUpdate({
    required this.uploadId,
    required this.status,
    this.assetId,
    this.error,
  });

  String uploadId;

  String status;

  String? assetId;

  String? error;

  List<Object?> _toList() {
    return <Object?>[
      uploadId,
      status,
      assetId,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static TusStatusUpdate decode(Object result) {
    result as List<Object?>;
    return TusStatusUpdate(
      uploadId: result[0]! as String,
      status: result[1]! as String,
      assetId: result[2] as String?,
      error: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TusStatusUpdate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is TusUploadData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is TusUploadResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is TusProgressUpdate) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is TusStatusUpdate) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return TusUploadData.decode(readValue(buffer)!);
      case 130: 
        return TusUploadResult.decode(readValue(buffer)!);
      case 131: 
        return TusProgressUpdate.decode(readValue(buffer)!);
      case 132: 
        return TusStatusUpdate.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API for tus upload operations (Dart calls native)
class TusUploadApi {
  /// Constructor for [TusUploadApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TusUploadApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Upload a file using the tus protocol
  /// Returns the upload ID that can be used to track progress or cancel
  Future<String> startUpload(TusUploadData data) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.immich_mobile.TusUploadApi.startUpload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[data]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Cancel an ongoing upload
  Future<bool> cancelUpload(String uploadId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.immich_mobile.TusUploadApi.cancelUpload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[uploadId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Cancel all ongoing uploads
  Future<void> cancelAllUploads() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.immich_mobile.TusUploadApi.cancelAllUploads$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get the current offset of an upload (for resumption)
  Future<int?> getUploadOffset(String uploadId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.immich_mobile.TusUploadApi.getUploadOffset$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[uploadId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as int?);
    }
  }

  /// Check if there are any pending uploads that can be resumed
  Future<List<String>> getPendingUploadIds() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.immich_mobile.TusUploadApi.getPendingUploadIds$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<String>();
    }
  }
}

/// Flutter API for receiving upload callbacks (native calls Dart)
abstract class TusUploadCallbackApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when upload progress changes
  void onProgress(TusProgressUpdate update);

  /// Called when upload status changes
  void onStatusChange(TusStatusUpdate update);

  static void setUp(TusUploadCallbackApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TusProgressUpdate? arg_update = (args[0] as TusProgressUpdate?);
          assert(arg_update != null,
              'Argument for dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onProgress was null, expected non-null TusProgressUpdate.');
          try {
            api.onProgress(arg_update!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onStatusChange$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onStatusChange was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TusStatusUpdate? arg_update = (args[0] as TusStatusUpdate?);
          assert(arg_update != null,
              'Argument for dev.flutter.pigeon.immich_mobile.TusUploadCallbackApi.onStatusChange was null, expected non-null TusStatusUpdate.');
          try {
            api.onStatusChange(arg_update!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
